name: CI
on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm i

      - run: "git branch --track ${{github.base_ref}} origin/${{github.base_ref}}"
      - run: "git branch --track ${{github.head_ref}} origin/${{github.head_ref}}"
      - run: npx nx affected -t test --base=main --head=vinicius-pimenta

